### ISSUE TITLE
Possibly Unexpected Behavior with Entry Number in Batch Logging

### ISSUE THREAD

**Issue by starkguerraj** [jongpie/NebulaLogger#227] opened 2021-10-12 16:17 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.6.9

### New Bug Summary

Using the Logger in a batch class it appears that entry numbers are duplicated across execute blocks.

I removed the irrelevant code from the class image.

![image](https://user-images.githubusercontent.com/72459978/136992336-d7422ee4-a0f5-47be-9874-60b5c898bf2a.png)

![image](https://user-images.githubusercontent.com/72459978/136992637-e7f93c5b-e9f3-4646-8e8f-6e6ca35058cb.png)

**Comment by starkguerraj** [comment] 2021-10-12 17:32
Sure, hopefully its something obvious when you get around to looking at it.

Definitely let me know if there's anything else I can provide.

**Comment by jongpie** [comment] 2022-05-11 19:16
@starkguerraj apologies for not getting back to you on this sooner, but I've been trying to reproduce this issue in some of the newer versions of Nebula Logger, and haven't been able to do so yet. Is this issue still happening for you?

**Comment by jongpie** [comment] 2022-06-01 03:50
@starkguerraj another follow up on this - I _think_ that this issue was fixed in [v4.7.3](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.3), where I introduced a changed related to #310. I was never able to successfully reproduce your specific issue within a batch job, but it still seems to be the same issue. Specifically, the issue seemed to be Nebula Logger's usage of `System.Request.getCurrent().getRequestId()` as the value for `Logger.getTransactionId()` - it turns out that the value returned from `System.Request.getCurrent().getRequestId()` is not necessarily unique, resulting in `LogEntry__c` records from different transactions being combined into a single `Log__c` record for queueable jobs (and presumably, batchable jobs). As of v4.7.3, I've reverted to always using a custom `UUID` value as the unique transaction ID, which should avoid this issue going forward.

I'm going to go ahead and close this issue, but if you encounter it again, please let me know!

**Closed by jongpie** 2022-06-01 03:50 UTC
Labels: bug, can't reproduce, log retention
