### ISSUE TITLE
Unable to uninstall unlocked package

### ISSUE THREAD

**Issue by stephenpstanley** [jongpie/NebulaLogger#735] opened 2024-08-17 05:50 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.13.14

### New Bug Summary

I have managed to get both the Managed and unlocked package installed in an org and I want to remove the unlocked version. When trying to install it, I get this list of issues.  These are no jobs scheduled that I can find that refer to the package Apex classes not any sharing rules that related to the objects.

How can I delete the package so all my logs can be in just one place?
![image](https://github.com/user-attachments/assets/8dc77551-ee4c-4f09-b9af-c89b88ca0c74)

**Comment by stephenpstanley** [comment] 2024-08-17 07:02
Some of the issues were because there were some custom APEX classes that were using the unlocked package, but now that they have all been removed, I'm getting this 
![image](https://github.com/user-attachments/assets/c4c1f4a0-2940-4b7f-b499-a56547c67718)

**Comment by stephenpstanley** [comment] 2024-08-17 23:48
I thought it might because of some (unlikely) dependency between unlocked package and managed package but maybe not. Even having uninstalled the managed package, I still can't uninstall the unlocked package. I'm still getting the dependency issues above

**Comment by stephenpstanley** [comment] 2024-08-17 23:52
...and for some reason, the dependency violations list has just grown longer 
![image](https://github.com/user-attachments/assets/9f072fe4-c2a8-40e8-b440-a7c132769d7c)

**Comment by jongpie** [comment] 2024-08-19 14:54
@stephenpstanley this is definitely strange, I don't think I've seen this behavior before, and those specific errors are all.... interesting 😅 
- Some of the errors have been about the Apex class `ComponentLogger` and the LWC `logger` - is there any chance you have references to `logger` LWC in any of your own LWCs or Aura components?
- The `loggerSettings` LWC shown in some of your screenshots too - that LWC is used by the custom tab "Logger Settings" - is there any chance your profiles or permission sets have been given access to the custom tab?

Let me know what you find - I'm not 100% sure what else could be causing this, but hopefully we can figure this out.

**Comment by stephenpstanley** [comment] 2024-08-19 22:10
I ended up taking a pragmatic approach so no longer have the problem. 
I deleted all the packages Tabs and deactivated and deleted all the Lightning Pages in the package
I did a destructive deployment which got rid of the LWC that it was complaining about but I couldn't get rid of the APEX class(es) that way as they had other dependencies.  In the end I edited the classes in a sandbox, removed all the code except one line for test coverage and created a test class that exercised that line.  I then deployed that to production using a change set and did a destructive deployment on that.  Once I'd done that I was able to delete the package.

Answers to your thoughts.
- I had no Lightning Web Components or Aura components doing any logging - only APEX Classes and Flows
- I don't think that any profiles or permission sets were used to give access to the custom tab - I was only assigning the permsets that came in the package

**Comment by jongpie** [comment] 2024-08-20 15:01
@stephenpstanley thanks for all of the context - it sounds like you had to go through a _lot_ of hassle to work around this. I'm still not sure what would have caused this issue, I frequently test in orgs that have both the unlocked & managed package installed without any issues, and I've never heard of anyone else encountering these issues before. 

My thought is that this is probably an issue on the Salesforce side (and not an issue with Nebula Logger itself), all of the metadata referenced in those errors is part of Nebula Logger's metadata that should be removed anyway. I'm going to keep it open for now & will try to look into this a bit more to see if I can recreate those errors. But since you were able to workaround the problem, I'll eventually close this issue if I'm not able to reproduce it.

If you run into any other issues, please let me know!

**Comment by stephenpstanley** [comment] 2024-08-20 20:21
I shouldn’t sweat it too much - there are probably more important things to work on 

it sounds like a real outlier and isn’t causing me problems any more.

**Comment by jongpie** [comment] 2024-08-20 20:23
@stephenpstanley sounds good, I appreciate that - I'll spend a few minutes trying to recreate the issue (just to see if I can), but if I can't, I'll close this out.

**Comment by jongpie** [comment] 2024-08-22 23:25
@stephenpstanley I did some more testing with the unlocked package to try to reproduce this, and unfortunately wasn't able to do so. I'll go ahead and close this for now & mark it as `wontfix`, but if you/anyone else runs into this again, I can reopen it & look into it further.

**Closed by jongpie** 2024-08-22 23:25 UTC
Labels: Type: Bug
