### ISSUE TITLE
Tests failing due to "permission set assigned"

### ISSUE THREAD

**Issue by Manishjodhani** [jongpie/NebulaLogger#546] opened 2023-09-14 09:32 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.10.6

### New Bug Summary

 I'm getting a test failure when running a deployment:

 - Error Message: ****System.AssertException: Assertion Failed: permission set assigned
- External entry point. Class.LogBatchPurgeController_Tests.it_should_not_permit_user_to_execute_purge_batch_when_custom_permission_is_not_assigned: line 372, column 1

**Comment by KushalB** [comment] 2023-09-25 22:50
I can look at this to see if I can fix it.

**Comment by jongpie** [comment] 2023-09-26 03:13
@KushalB that would be amazing! Once you've had a chance to look at it, let me know your thoughts (or if you have any questions that I can help with).

**Comment by Manishjodhani** [comment] 2023-09-26 05:33
Hi @KushalB ,
Standard users had permission to execute the purge batch, but I removed the permission and it fixed the issue.

**Comment by KushalB** [comment] 2023-09-26 15:11
@jongpie seams like the issue is resolved based on @Manishjodhani 's comment.

**Comment by jongpie** [comment] 2023-09-27 17:45
@KushalB yeah, I think we can hold off on making any changes for this - typically, orgs don't provide access to the Standard user profile, so I don't think this is a common problem.

I'll close this for now - @Manishjodhani, let me know if you need anything else!

**Closed by jongpie** 2023-09-27 17:45 UTC
Labels: bug, tests
