### ISSUE TITLE
Test Failing in CI 

### ISSUE THREAD

**Issue by rafahg** [jongpie/NebulaLogger#478] opened 2023-04-06 16:53 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.10

### New Bug Summary

Hi, 

We are installing nebula logger as an Unlocked package as part of our CI build in a github action. 

I am running our localtests in the action using this command : 

`sfdx apex run test --target-org ciorg --wait 10 --result-format junit --output-dir ./unit-test-results --code-coverage --test-level RunLocalTests`

And the build is failing in the test : 

`LoggerSObjectProxy_Tests/it_converts_network_record_to_proxy: System.QueryException: List has no rows for assignment to SObject
Class.LoggerSObjectProxy_Tests.it_converts_network_record_to_proxy: line 82, column 1`

I understand that the test is failing because the Scratch org we create in the action is created, in our case,  with the experience cloud enabled, therefore the failure, as no network is  found and the query for that test fails.

My question is though , the flag 'RunLocalTest' should not avoid the tests coming from an Unlocked package to run in any case?

Thanks!

**Comment by MeStrak** [comment] 2023-04-06 22:08
Annoying SF issue about this issue of package tests running when they probably shouldn't according to the CLI flag: 
https://issues.salesforce.com/issue/a028c00000gAzBtAAK/sfdx-forceapextestrun-runlocaltests-doesnt-work-correctly-for-the-unlocked-package-apex-test-classes

@jongpie Rafa is also part of the LEGO team! 😎

**Comment by jongpie** [comment] 2023-04-09 02:04
Hi @rafahg & @MeStrak! I'm still really excite to hear that LEGO is using Nebula Logger 🧱 🥳  I can fix this test failure in the next release (`v4.10.1`) that should hopefully be released within the next few days. 

As far as why the tests are running, I think this is unfortunately expected behavior - when you use `--test-level RunLocalTests`, the way that Salesforce determines "local" tests is based only on the namespace (or lack thereof), regardless if the metadata is part of a package. In this case, Nebula Logger's unlocked package doesn't have a namespace, so its code is considered "local" in your org (along with your own code). I'd love for Salesforce to introduce a way to exclude local tests that are part of a package, but I'm not sure if/when that will ever be added to sfdx.

For what it's worth, I'm constantly trying to improve the speed of Nebula Logger's tests, and I hope to make some more speed improvements over the next month or two. Alternatively, if you don't want to run Nebula Logger's tests in your pipeline, you could create [an Apex test suite](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_apextestsuite.htm) for your Apex tests, and update your pipeline to use something like this command (assuming you create a test suite called "My_Test_Suite"):

`sfdx apex run test --target-org ciorg --wait 10 --result-format junit --output-dir ./unit-test-results --code-coverage --suitenames My_Test_Suite`

This isn't really ideal either, since this would require you to create & maintain a test suite - but it would provide a way to only run your tests in your pipeline.

**Comment by rafahg** [comment] 2023-04-09 08:18
Thanks so much for you detailed answer @jongpie . I’ve solved the issue for the time being in a similar way of what you propose. That will work fine until the next release you mention in you answer.

  One of the main reasons which convinced us to incorporate nebula logger to our Salesforce product in LEGO after considering different options is precisely that we appreciated that you mantein and support this package with a lot of care and diligence.  Keep up the excellent work. 
  
      Rafa

**Closed** 2023-04-09 08:18 UTC
Labels: bug, tests

**Comment by jongpie** [comment] 2023-04-10 16:13
@rafahg that test failure should now be resolved in the latest release, [`v4.10.1`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.10.1). If you run into any other issues, please let me know!
