### ISSUE TITLE
saveLog action is not performed correctly on Lightning Component

### ISSUE THREAD

**Issue by stefanocortellessa** [jongpie/NebulaLogger#556] opened 2023-09-22 09:23 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.11.4

### New Bug Summary

We are using Nebula Logger on an LWC and we are experiencing a failure in adding Log Entries that are inserted just before the save action. 
The settings are reported below:
![nebula logger settings](https://github.com/jongpie/NebulaLogger/assets/17218375/616f9f30-f89a-4804-aeb3-1e2d5072da05)

The code below results in a missing log, since it seems that the save log action is not captured correctly by the saveLog function. 
![saveLog Issue](https://github.com/jongpie/NebulaLogger/assets/17218375/07d518c7-ecb0-44ad-ba36-509cb18fe929)

We figured out that if we create a log entry in an action that is executed before the handleClick function, for example in a connectedCallback, the result is an incomplete log. In particular, the last Log Entry added into the handleClick function is missing.
You can find an example below:
![saveLog Issue - connectedCallback](https://github.com/jongpie/NebulaLogger/assets/17218375/c18dbd14-b9aa-4e7c-a7c2-4f3ed5351d24)

![Log Result](https://github.com/jongpie/NebulaLogger/assets/17218375/5408ce77-1ff4-4759-895a-1cdb8286139a)

I want to underline that the issue also occurs in _Aura components._
Are you able to tell me, on a technical level, _**_why this behavior occurs_**_?

**Comment by jongpie** [comment] 2023-09-26 02:49
Hi @stefanocortellessa - this sounds like the same issue as #518, so I'll close this out as a duplicate. 

As far as why this is occurring, the issue is that adding new entries (using functions like `logger.error()`, `logger.warn()`, `logger.info()`, etc.) happens asynchronously, but the `saveLog()` function runs synchronously - so when you log something & then immediately try to save it, the `logger` LWC has inconsistent/problematic results.

**Closed by jongpie** 2023-09-26 02:49 UTC
Labels: bug, duplicate, lightning components, logger engine
