### ISSUE TITLE
Logger.error(String, SObject) fails with Platform Events (Invalid Field Id)

### ISSUE THREAD

**Issue by dschibster** [jongpie/NebulaLogger#325] opened 2022-06-07 11:24 UTC
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.2.7.1

### New Bug Summary

Hi @jongpie 

Nebula Logger has been a lifesaver for a recent project of mine where we implemented it as an integral part of our pipeline and for monitoring of our event-based external integration. 

This logging however seems to be causing us an issue currently, as we are facing an issue when trying to log an error coming from a platform event itself:

`Invalid field id` is what is coming up in these cases. Probably still from an implementation expecting completely full-fledged SObject records to come up there, but in our case it's an actual event that we want to make part of this log. We'd either have to make it ugly by appending the Event JSON or see how it can be fixed.

Has this been addressed in later versions or is this a new error?

Thanks in advance!

**Comment by jongpie** [comment] 2022-06-07 13:13
Hi @dschibster - would it be possible for you to provide a stack trace for this error and/or an example script to reproduce the issue? And can you clarify which version of Nebula Logger you're using? This bug lists "v4.2.7.1", which seems like it has an extra digit in it (maybe "v4.7.1" is the version you're using?). It looks like I don't have a unit test to specifically cover logging platform events, but when I just tested it in a scratch org, it seems to be working - I'm not able to reproduce the issue `Invalid field id`. I haven't made any recent changes to this part of the code, so it's strange that it works for me but fails for you, but I might be going about this the wrong way to test it. For example, this works for me:

```java
// Here, I'm using LogEntryEvent__e as an example platform event, since it's already available as part of Nebula Logger
// But the same idea should work for any platform event
Logger.error('hello', new LogEntryEvent__e(Message__c = 'example logging of a platform event'));
Logger.saveLog();
```

This saves successfully, and the `LogEntry__c` record has the platform event's JSON populated

![image](https://user-images.githubusercontent.com/1267157/172386838-ea3aea63-2330-4b95-8da8-eb1714b32449.png)

If I run this script (which does not reference Nebula Logger at all, it just uses Nebula Logger's platform event object), then it still works without any issues, so I'm not sure how to reproduce the error you're seeing.

```java
LogEntryEvent__e e = new LogEntryEvent__e();
System.debug(e.Id); // This outputs null, but no error
```

Let me know if you can provide some more details - my hope is that we can get this solved for you fairly quickly.

**Comment by jongpie** [comment] 2022-06-07 14:30
Thanks @dschibster! I'll do look at this log & will do some more testing to see if I can reproduce the issue. I'll let you know if I have any follow up questions.

**Comment by jongpie** [comment] 2022-09-26 18:10
Hi @dschibster - just wanted to follow up on this, are you still having this issue? I've been trying to reproduce the issue, but have not had any luck so far.

**Comment by jongpie** [comment] 2024-01-29 17:31
@dschibster I'm going to close this issue for now - I have not been able to reproduce the issue. But if you're still having this issue, please let me know & I can look into it again.

**Closed by jongpie** 2024-01-29 17:31 UTC
Labels: bug, logger engine, can't reproduce

**Comment by dschibster** [comment] 2024-01-29 21:32
Hi @jongpie sorry I didn't answer beforehand. We ended up not running into this issue after upgrading the version of Nebula Logger. Can't quite say what it was coming from but it was fine after. :)

**Comment by jongpie** [comment] 2024-01-30 02:28
@dschibster no worries, glad to hear that it's working in newer versions! If you have any other issues, just let me know.

**Comment by jongpie** [comment] 2025-09-10 20:28
Hi @bnockerts - is it possible for you to upgrade to a newer version of Nebula Logger (in a sandbox), and see if you still have this issue?
