### ISSUE TITLE
System.QueryException: unexpected token: '('

### ISSUE THREAD

**Issue by daveerickson** [jongpie/NebulaLogger#131] opened 2021-04-16 20:31 UTC
Received exception email.
```
Users: execution of BeforeUpdate

caused by: System.QueryException: unexpected token: '('

Class.LogEntryEventBuilder.getNetwork: line 752, column 1
Class.LogEntryEventBuilder: line 16, column 1
Class.Logger.newEntry: line 4894, column 1
Class.Logger.newEntry: line 4890, column 1
Class.Logger.debug: line 4874, column 1
Class.Logger.debug: line 2905, column 1
Trigger.Users: line 3, column 1
```
I have a trigger, Users, that calls Logger.debug('...') on line 3. This error was thrown by an external user who does not have an assigned permission set to create logs. Here's what I've found out so far.

The pertinent code from LogEntryEventBuilder, Line 750
```
String queryString = 'SELECT Id, Name, UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId()';

return Database.query(queryString);
```
If I remove the return statement and run from Anonymous Apex
```
String queryString = 'SELECT Id, Name, UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId()';
System.debug(Database.query(queryString));
```
I receive the same error
`System.QueryException: unexpected token: '('`

If I don't run it as Dynamic SOQL it works fine
```
System.debug([SELECT Id, Name, UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId()]);
```
If I save the Id from Network.getNetworkId() to a variable and bind to that then the Dynamic SOQL works
```
Id getNetworkId = Network.getNetworkId();
String queryString = 'SELECT Id, Name, UrlPathPrefix FROM Network WHERE Id = :getNetworkId';
System.debug(Database.query(queryString));
```
I didn't submit a PR, because frankly this doesn't make sense to me. Sure, setting an Id before 'fixes' the issue, but I wouldn't expect the same query to behave differently run directly from SOQL vs Dynamic SOQL. I'd like confirmation that this behaves the same for others, but assuming it is a legitimate bug it may make the most sense to capture the Id as part of the if statement on line 738
```
if (Network.getNetworkId() == null) {
    return null;
}
```
to
```
Id networkId;
if (Network.getNetworkId() == null) {
    return null;
} else {
    networkId = Network.getNetworkId();
}
```

**Comment by jongpie** [comment] 2021-04-19 22:09
Hi @daveerickson thanks for reporting this issue! This definitely seems strange, but I was able to reproduce the issue in a scratch org, so it definitely seems like a legitmate bug. I completely agree that the SOQL vs dynamic SOQL should behave the same, so it's a strange issue. But I think your `if/else` statement will circumvent the issue - I can put in a fix for this later this week (or you're welcome to submit a PR if you'd like)

**Comment by daveerickson** [comment] 2021-04-20 14:06
Thank you for confirming, I'm still scratching my head over it. I'll see if I can get a PR in before you.

**Comment by shahartal80** [comment] 2021-04-25 18:31
Hi @jongpie - we're also waiting for the fix on this one.

**Closed** 2021-04-25 20:01 UTC
Labels: bug

**Comment by jongpie** [comment] 2021-04-25 20:08
@shahartal80 this is now fixed in the `main` branch - @daveerickson made the fixes in PR #135.

Thanks again @daveerickson for working on the fix!

**Comment by shahartal80** [comment] 2021-04-25 20:25
@jongpie Thanks so much for the quick approval of the PR and thanks @daveerickson for the quick fix!
@jongpie is this now available in the managed package also, or only the unmanaged at this point?

**Comment by jongpie** [comment] 2021-04-25 20:59
Hi @shahartal80 - currently, the fix is only available in the unmanaged version. I'm hoping to release a new version of the managed package within the next week (and it'll include this bugfix)

**Comment by shahartal80** [comment] 2021-04-25 21:05
> Hi @shahartal80 - currently, the fix is only available in the unmanaged version. I'm hoping to release a new version of the managed package within the next week (and it'll include this bugfix)

THANKS!

**Comment by shahartal80** [comment] 2021-05-02 12:56
> Hi @shahartal80 - currently, the fix is only available in the unmanaged version. I'm hoping to release a new version of the managed package within the next week (and it'll include this bugfix)

Hi @jongpie - any news re the new version for the managed package?

**Comment by jongpie** [comment] 2021-05-03 01:40
Hi @shahartal80 - I still need to finalize some testing on the new version of the package (see PR #142), but I'm hoping to have it completely in the next day or two.

**Comment by shahartal80** [comment] 2021-05-03 07:07
Great news @jongpie  Thanks!

**Comment by shahartal80** [comment] 2021-05-09 07:17
> Hi @shahartal80 - I still need to finalize some testing on the new version of the package (see PR #142), but I'm hoping to have it completely in the next day or two.

Hi @jongpie - Any news re PR #142 and managed package? Thanks!

**Comment by jongpie** [comment] 2021-05-10 21:47
Hey @shahartal80 sorry for the delay! I think the latest release is more or less ready, but I'm unfortunately running into some issues with creating the next managed package version due to some strange unit test errors & failures. The issues might be related to the new Summer '21 release, but I'm looking into some options to handles the issues so I can get the next version released - I'm planning to spend time on it later this week and will have it published ASAP!

**Comment by shahartal80** [comment] 2021-05-18 08:28
Hi @jongpie , I hope everything is well on your end. I wanted to sync on the new managed package release, this holds us from starting to leverage Nebula logger. If PR #142 takes long to release due to the amount of changes included, is there any chance a lighter version with only a fix to the issue raised in issue #131 ? Thanks for the great work on this and the support!

**Comment by jongpie** [comment] 2021-05-20 05:34
@shahartal80 so sorry for the delay, but [the new v4.4.0 release](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.0) is finally done & released! This includes the fix for this issue - let me know if you run into any other issues!

**Comment by shahartal80** [comment] 2021-05-20 07:18
@jongpie GREAT NEWS! This will allow us to move our changes to UAT at this point. One nice thing I want to mention that platform events allowed us to leverage - we created a java client that picks the log events, so you get some sort of a real time console through your development and testing of the solution that is running in salesforce. We are also looking to index the logs through splunk. Thanks again for your hard work on this one!

**Comment by yazuminsu** [comment] 2024-06-27 06:00
I encountered the same issue but with ActionPlanItem object.

I get the error when I run

`List<ActionPlanItem> actionPItems = Database.query('SELECT ID, ActionPlanId, Name FROM ActionPlanItem WHERE ActionPlanId IN :actionPlans.keySet()');`

but no error on below

`List<ActionPlanItem> actionPItems = [SELECT ID, ActionPlanId, Name FROM ActionPlanItem WHERE ActionPlanId IN :actionPlans.keySet()];`
